# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you chanhttps://www.andrewhorner.comhttps://www.andrewhorner.comge this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: tara joy dev
email: tarajoy@posteo.net
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# For user/organization sites, baseurl should be empty
baseurl: "" # the subpath of your site, e.g. /blog

# Set your custom domain here
url: "https://tarajoy.dev" # the base hostname & protocol for your site

twitter_username: tara-joy
github_username: tara-joy

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed
sass:
  sass_dir: _sass
# Exclude from processing.
# Uncomment and edit as needed
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
